name: test
on:
  push:
    branches:
      - '*'
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Add mask
        run: |
          echo "::add-mask::${{ secrets.EXTENSION_ID }}" &&
          echo "::add-mask::${{ secrets.JWT_ISSUER }}" &&
          echo "::add-mask::${{ secrets.JWT_SECRET }}"
      - run: npm install
      - run: npm test
        env:
          EXTENSION_ID: ${{secrets.EXTENSION_ID}}
          JWT_ISSUER: ${{secrets.JWT_ISSUER}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
